name = "smart-grocer-frontend"
compatibility_date = "2025-10-27"
compatibility_flags = ["nodejs_compat"]

# Static site configuration
[site]
bucket = "./dist"

[build]
command = "npm run build"

# Workers Site configuration
main = "./workers-site/index.js"